name: Code Quality and Tests
on:
  push:
    branches:
      - main
      - staging

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code ğŸ›ï¸
        uses: actions/checkout@v2

      - name: Setup Conda ğŸ”§
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yaml  # Create an environment.yml file
          activate-environment: my-template-environment
          auto-activate-base: false
      - run: |
          conda info
          conda list

      - name: Setup Node ğŸ”§
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install click using Conda
        run: |
          conda list
          conda install -c anaconda click

      - name: Run isort
        run: isort --check-only --profile black .

      - name: Run Black
        run: black --check .

      - name: Run flake8
        run: flake8 . --exclude setup.py

      - name: Run ruff
        run: ruff --fix --exit-non-zero-on-fix .

      - name: Run interrogate
        run: interrogate src -v -i --fail-under=60 -e '**/__init__.py'

      - name: Bandit Security Linter
        run: bandit -c pyproject.toml -r .

      - name: Run Pytest
        run: pytest tests/
